### ISSUE TITLE
Warning: Error in file: 无法打开链结

### ISSUE THREAD

**Issue by yangwukaidi** [gc5k/EigenGWASRshiny#3]
Hi，
Local RStudio operation encountered an error, could you tell me how to solve？
![1701333837842](https://github.com/gc5k/EigenGWASRshiny/assets/127917612/f0085899-2106-40ee-a0ef-fb65dab94e42)

**Comment by gc5k** [comment]
Probably because your dir contains "林唐“. Could you try it again without Chinese characters.
